import React  from 'react';
import { ConfigProvider, Select } from 'antd';
const {Option} = Select
export default function CountrySelect()  {
    
    const countries = [
        { label: 'Afghanistan', value: '(+93)', ccTLD: '🇦🇫' },
        { label: 'Aland Islands', value: '(+358)', ccTLD: '🇦🇽' },
        { label: 'Albania', value: '(+355)', ccTLD: '🇦🇱' },
        { label: 'Algeria', value: '(+213)', ccTLD: '🇩🇿' },
        { label: 'American Samoa', value: '(+1684)', ccTLD: '🇦🇸' },
        { label: 'Andorra', value: '(+376)', ccTLD: '🇦🇩' },
        { label: 'Angola', value: '(+244)', ccTLD: '🇦🇴' },
        { label: 'Anguilla', value: '(+1264)', ccTLD: '🇦🇮' },
        { label: 'Antarctica', value: '(+672)', ccTLD: '🇦🇶' },
        { label: 'Antigua and Barbuda', value: '(+1268)', ccTLD: '🇦🇬' },
        { label: 'Argentina', value: '(+54)', ccTLD: '🇦🇷' },
        { label: 'Armenia', value: '(+374)', ccTLD: '🇦🇲' },
        { label: 'Aruba', value: '(+297)', ccTLD: '🇦🇼' },
        { label: 'Australia', value: '(+61)', ccTLD: '🇦🇺' },
        { label: 'Austria', value: '(+43)', ccTLD: '🇦🇹' },
        { label: 'Azerbaijan', value: '(+994)', ccTLD: '🇦🇿' },
        { label: 'Bahamas', value: '(+1242)', ccTLD: '🇧🇸' },
        { label: 'Bahrain', value: '(+973)', ccTLD: '🇧🇭' },
        { label: 'Bangladesh', value: '(+880)', ccTLD: '🇧🇩' },
        { label: 'Barbados', value: '(+1246)', ccTLD: '🇧🇧' },
        { label: 'Belarus', value: '(+375)', ccTLD: '🇧🇾' },
        { label: 'Belgium', value: '(+32)', ccTLD: '🇧🇪' },
        { label: 'Belize', value: '(+501)', ccTLD: '🇧🇿' },
        { label: 'Benin', value: '(+229)', ccTLD: '🇧🇯' },
        { label: 'Bermuda', value: '(+1441)', ccTLD: '🇧🇲' },
        { label: 'Bhutan', value: '(+975)', ccTLD: '🇧🇹' },
        { label: 'Bolivia', value: '(+591)', ccTLD: '🇧🇴' },
        { label: 'Bonaire, Sint Eustatius and Saba', value: '(+599)', ccTLD: '🇧🇶' },
        { label: 'Bosnia and Herzegovina', value: '(+387)', ccTLD: '🇧🇦' },
        { label: 'Botswana', value: '(+267)', ccTLD: '🇧🇼' },
        { label: 'Bouvet Island', value: '(+55)', ccTLD: '🇧🇻' },
        { label: 'Brazil', value: '(+55)', ccTLD: '🇧🇷' },
        { label: 'British Indian Ocean Territory', value: '(+246)', ccTLD: '🇮🇴' },
        { label: 'Brunei Darussalam', value: '(+673)', ccTLD: '🇧🇳' },
        { label: 'Bulgaria', value: '(+359)', ccTLD: '🇧🇬' },
        { label: 'Burkina Faso', value: '(+226)', ccTLD: '🇧🇫' },
        { label: 'Burundi', value: '(+257)', ccTLD: '🇧🇮' },
        { label: 'Cambodia', value: '(+855)', ccTLD: '🇰🇭' },
        { label: 'Cameroon', value: '(+237)', ccTLD: '🇨🇲' },
        { label: 'Canada', value: '(+1)', ccTLD: '🇨🇦' },
        { label: 'Cape Verde', value: '(+238)', ccTLD: '🇨🇻' },
        { label: 'Cayman Islands', value: '(+1345)', ccTLD: '🇰🇾' },
        { label: 'Central African Republic', value: '(+236)', ccTLD: '🇨🇫' },
        { label: 'Chad', value: '(+235)', ccTLD: '🇹🇩' },
        { label: 'Chile', value: '(+56)', ccTLD: '🇨🇱' },
        { label: 'China', value: '(+86)', ccTLD: '🇨🇳' },
        { label: 'Christmas Island', value: '(+61)', ccTLD: '🇨🇽' },
        { label: 'Cocos (Keeling) Islands', value: '(+672)', ccTLD: '🇨🇨' },
        { label: 'Colombia', value: '(+57)', ccTLD: '🇨🇴' },
        { label: 'Comoros', value: '(+269)', ccTLD: '🇰🇲' },
        { label: 'Congo', value: '(+242)', ccTLD: '🇨🇬' },
        { label: 'Congo, Democratic Republic of the Congo', value: '(+242)', ccTLD: '🇨🇩' },
        { label: 'Cook Islands', value: '(+682)', ccTLD: '🇨🇰' },
        { label: 'Costa Rica', value: '(+506)', ccTLD: '🇨🇷' },
        { label: "Cote D'Ivoire", value: '(+225)', ccTLD: '🇨🇮' },
        { label: 'Croatia', value: '(+385)', ccTLD: '🇭🇷' },
        { label: 'Cuba', value: '(+53)', ccTLD: '🇨🇺' },
        { label: 'Curacao', value: '(+599)', ccTLD: '🇨🇼' },
        { label: 'Cyprus', value: '(+357)', ccTLD: '🇨🇾' },
        { label: 'Czech Republic', value: '(+420)', ccTLD: '🇨🇿' },
        { label: 'Denmark', value: '(+45)', ccTLD: '🇩🇰' },
        { label: 'Djibouti', value: '(+253)', ccTLD: '🇩🇯' },
        { label: 'Dominica', value: '(+1767)', ccTLD: '🇩🇲' },
        { label: 'Dominican Republic', value: '(+1809)', ccTLD: '🇩🇴' },
        { label: 'Ecuador', value: '(+593)', ccTLD: '🇪🇨' },
        { label: 'Egypt', value: '(+20)', ccTLD: '🇪🇬' },
        { label: 'El Salvador', value: '(+503)', ccTLD: '🇸🇻' },
        { label: 'Equatorial Guinea', value: '(+240)', ccTLD: '🇬🇶' },
        { label: 'Eritrea', value: '(+291)', ccTLD: '🇪🇷' },
        { label: 'Estonia', value: '(+372)', ccTLD: '🇪🇪' },
        { label: 'Ethiopia', value: '(+251)', ccTLD: '🇪🇹' },
        { label: 'Falkland Islands (Malvinas)', value: '(+500)', ccTLD: '🇫🇰' },
        { label: 'Faroe Islands', value: '(+298)', ccTLD: '🇫🇴' },
        { label: 'Fiji', value: '(+679)', ccTLD: '🇫🇯' },
        { label: 'Finland', value: '(+358)', ccTLD: '🇫🇮' },
        { label: 'France', value: '(+33)', ccTLD: '🇫🇷' },
        { label: 'French Guiana', value: '(+594)', ccTLD: '🇬🇫' },
        { label: 'French Polynesia', value: '(+689)', ccTLD: '🇵🇫' },
        { label: 'French Southern Territories', value: '(+262)', ccTLD: '🇹🇫' },
        { label: 'Gabon', value: '(+241)', ccTLD: '🇬🇦' },
        { label: 'Gambia', value: '(+220)', ccTLD: '🇬🇲' },
        { label: 'Georgia', value: '(+995)', ccTLD: '🇬🇪' },
        { label: 'Germany', value: '(+49)', ccTLD: '🇩🇪' },
        { label: 'Ghana', value: '(+233)', ccTLD: '🇬🇭' },
        { label: 'Gibraltar', value: '(+350)', ccTLD: '🇬🇮' },
        { label: 'Greece', value: '(+30)', ccTLD: '🇬🇷' },
        { label: 'Greenland', value: '(+299)', ccTLD: '🇬🇱' },
        { label: 'Grenada', value: '(+1473)', ccTLD: '🇬🇩' },
        { label: 'Guadeloupe', value: '(+590)', ccTLD: '🇬🇵' },
        { label: 'Guam', value: '(+1671)', ccTLD: '🇬🇺' },
        { label: 'Guatemala', value: '(+502)', ccTLD: '🇬🇹' },
        { label: 'Guernsey', value: '(+44)', ccTLD: '🇬🇬' },
        { label: 'Guinea', value: '(+224)', ccTLD: '🇬🇳' },
        { label: 'Guinea-Bissau', value: '(+245)', ccTLD: '🇬🇼' },
        { label: 'Guyana', value: '(+592)', ccTLD: '🇬🇾' },
        { label: 'Haiti', value: '(+509)', ccTLD: '🇭🇹' },
        { label: 'Heard Island and Mcdonald Islands', value: '(+672)', ccTLD: '🇭🇲' },
        { label: 'Holy See (Vatican City State)', value: '(+379)', ccTLD: '🇻🇦' },
        { label: 'Honduras', value: '(+504)', ccTLD: '🇭🇳' },
        { label: 'Hong Kong', value: '(+852)', ccTLD: '🇭🇰' },
        { label: 'Hungary', value: '(+36)', ccTLD: '🇭🇺' },
        { label: 'Iceland', value: '(+354)', ccTLD: '🇮🇸' },
        { label: 'India', value: '(+91)', ccTLD: '🇮🇳' },
        { label: 'Indonesia', value: '(+62)', ccTLD: '🇮🇩' },
        { label: 'Iran, Islamic Republic of Persian Gulf', value: '(+98)', ccTLD: '🇮🇷' },
        { label: 'Iraq', value: '(+964)', ccTLD: '🇮🇶' },
        { label: 'Ireland', value: '(+353)', ccTLD: '🇮🇪' },
        { label: 'Isle of Man', value: '(+44)', ccTLD: '🇮🇲' },
        { label: 'Israel', value: '(+972)', ccTLD: '🇮🇱' },
        { label: 'Italy', value: '(+39)', ccTLD: '🇮🇹' },
        { label: 'Jamaica', value: '(+1876)', ccTLD: '🇯🇲' },
        { label: 'Japan', value: '(+81)', ccTLD: '🇯🇵' },
        { label: 'Jersey', value: '(+44)', ccTLD: '🇯🇪' },
        { label: 'Jordan', value: '(+962)', ccTLD: '🇯🇴' },
        { label: 'Kazakhstan', value: '(+7)', ccTLD: '🇰🇿' },
        { label: 'Kenya', value: '(+254)', ccTLD: '🇰🇪' },
        { label: 'Kiribati', value: '(+686)', ccTLD: '🇰🇮' },
        { label: "Korea, Democratic People's Republic of Korea", value: '(+850)', ccTLD: '🇰🇵' },
        { label: 'Korea, Republic of South Korea', value: '(+82)', ccTLD: '🇰🇷' },
        { label: 'Kuwait', value: '(+965)', ccTLD: '🇰🇼' },
        { label: 'Kyrgyzstan', value: '(+996)', ccTLD: '🇰🇬' },
        { label: "Lao People's Democratic Republic", value: '(+856)', ccTLD: '🇱🇦' },
        { label: 'Latvia', value: '(+371)', ccTLD: '🇱🇻' },
        { label: 'Lebanon', value: '(+961)', ccTLD: '🇱🇧' },
        { label: 'Lesotho', value: '(+266)', ccTLD: '🇱🇸' },
        { label: 'Liberia', value: '(+231)', ccTLD: '🇱🇷' },
        { label: 'Libyan Arab Jamahiriya', value: '(+218)', ccTLD: '🇱🇾' },
        { label: 'Liechtenstein', value: '(+423)', ccTLD: '🇱🇮' },
        { label: 'Lithuania', value: '(+370)', ccTLD: '🇱🇹' },
        { label: 'Luxembourg', value: '(+352)', ccTLD: '🇱🇺' },
        { label: 'Macao', value: '(+853)', ccTLD: '🇲🇴' },
        { label: 'Macedonia', value: '(+389)', ccTLD: '🇲🇰' },
        { label: 'Madagascar', value: '(+261)', ccTLD: '🇲🇬' },
        { label: 'Malawi', value: '(+265)', ccTLD: '🇲🇼' },
        { label: 'Malaysia', value: '(+60)', ccTLD: '🇲🇾' },
        { label: 'Maldives', value: '(+960)', ccTLD: '🇲🇻' },
        { label: 'Mali', value: '(+223)', ccTLD: '🇲🇱' },
        { label: 'Malta', value: '(+356)', ccTLD: '🇲🇹' },
        { label: 'Marshall Islands', value: '(+692)', ccTLD: '🇲🇭' },
        { label: 'Martinique', value: '(+596)', ccTLD: '🇲🇶' },
        { label: 'Mauritania', value: '(+222)', ccTLD: '🇲🇷' },
        { label: 'Mauritius', value: '(+230)', ccTLD: '🇲🇺' },
        { label: 'Mayotte', value: '(+262)', ccTLD: '🇾🇹' },
        { label: 'Mexico', value: '(+52)', ccTLD: '🇲🇽' },
        { label: 'Micronesia, Federated States of Micronesia', value: '(+691)', ccTLD: '🇫🇲' },
        { label: 'Moldova', value: '(+373)', ccTLD: '🇲🇩' },
        { label: 'Monaco', value: '(+377)', ccTLD: '🇲🇨' },
        { label: 'Mongolia', value: '(+976)', ccTLD: '🇲🇳' },
        { label: 'Montenegro', value: '(+382)', ccTLD: '🇲🇪' },
        { label: 'Montserrat', value: '(+1664)', ccTLD: '🇲🇸' },
        { label: 'Morocco', value: '(+212)', ccTLD: '🇲🇦' },
        { label: 'Mozambique', value: '(+258)', ccTLD: '🇲🇿' },
        { label: 'Myanmar', value: '(+95)', ccTLD: '🇲🇲' },
        { label: 'Namibia', value: '(+264)', ccTLD: '🇳🇦' },
        { label: 'Nauru', value: '(+674)', ccTLD: '🇳🇷' },
        { label: 'Nepal', value: '(+977)', ccTLD: '🇳🇵' },
        { label: 'Netherlands', value: '(+31)', ccTLD: '🇳🇱' },
        { label: 'Netherlands Antilles', value: '(+599)', ccTLD: '🇦🇳' },
        { label: 'New Caledonia', value: '(+687)', ccTLD: '🇳🇨' },
        { label: 'New Zealand', value: '(+64)', ccTLD: '🇳🇿' },
        { label: 'Nicaragua', value: '(+505)', ccTLD: '🇳🇮' },
        { label: 'Niger', value: '(+227)', ccTLD: '🇳🇪' },
        { label: 'Nigeria', value: '(+234)', ccTLD: '🇳🇬' },
        { label: 'Niue', value: '(+683)', ccTLD: '🇳🇺' },
        { label: 'Norfolk Island', value: '(+672)', ccTLD: '🇳🇫' },
        { label: 'Northern Mariana Islands', value: '(+1670)', ccTLD: '🇲🇵' },
        { label: 'Norway', value: '(+47)', ccTLD: '🇳🇴' },
        { label: 'Oman', value: '(+968)', ccTLD: '🇴🇲' },
        { label: 'Pakistan', value: '(+92)', ccTLD: '🇵🇰' },
        { label: 'Palau', value: '(+680)', ccTLD: '🇵🇼' },
        { label: 'Palestinian Territory, Occupied', value: '(+970)', ccTLD: '🇵🇸' },
        { label: 'Panama', value: '(+507)', ccTLD: '🇵🇦' },
        { label: 'Papua New Guinea', value: '(+675)', ccTLD: '🇵🇬' },
        { label: 'Paraguay', value: '(+595)', ccTLD: '🇵🇾' },
        { label: 'Peru', value: '(+51)', ccTLD: '🇵🇪' },
        { label: 'Philippines', value: '(+63)', ccTLD: '🇵🇭' },
        { label: 'Pitcairn', value: '(+64)', ccTLD: '🇵🇳' },
        { label: 'Poland', value: '(+48)', ccTLD: '🇵🇱' },
        { label: 'Portugal', value: '(+351)', ccTLD: '🇵🇹' },
        { label: 'Puerto Rico', value: '(+1939)', ccTLD: '🇵🇷' },
        { label: 'Qatar', value: '(+974)', ccTLD: '🇶🇦' },
        { label: 'Reunion', value: '(+262)', ccTLD: '🇷🇪' },
        { label: 'Romania', value: '(+40)', ccTLD: '🇷🇴' },
        { label: 'Russia', value: '(+7)', ccTLD: '🇷🇺' },
        { label: 'Rwanda', value: '(+250)', ccTLD: '🇷🇼' },
        { label: 'Saint Helena', value: '(+290)', ccTLD: '🇸🇭' },
        { label: 'Saint Kitts and Nevis', value: '(+1869)', ccTLD: '🇰🇳' },
        { label: 'Saint Lucia', value: '(+1758)', ccTLD: '🇱🇨' },
        { label: 'Saint Pierre and Miquelon', value: '(+508)', ccTLD: '🇵🇲' },
        { label: 'Saint Vincent and the Grenadines', value: '(+1784)', ccTLD: '🇻🇨' },
        { label: 'Samoa', value: '(+685)', ccTLD: '🇼🇸' },
        { label: 'San Marino', value: '(+378)', ccTLD: '🇸🇲' },
        { label: 'Sao Tome and Principe', value: '(+239)', ccTLD: '🇸🇹' },
        { label: 'Saudi Arabia', value: '(+966)', ccTLD: '🇸🇦' },
        { label: 'Senegal', value: '(+221)', ccTLD: '🇸🇳' },
        { label: 'Serbia', value: '(+381)', ccTLD: '🇷🇸' },
        { label: 'Seychelles', value: '(+248)', ccTLD: '🇸🇨' },
        { label: 'Sierra Leone', value: '(+232)', ccTLD: '🇸🇱' },
        { label: 'Singapore', value: '(+65)', ccTLD: '🇸🇬' },
        { label: 'Slovakia', value: '(+421)', ccTLD: '🇸🇰' },
        { label: 'Slovenia', value: '(+386)', ccTLD: '🇸🇮' },
        { label: 'Solomon Islands', value: '(+677)', ccTLD: '🇸🇧' },
        { label: 'Somalia', value: '(+252)', ccTLD: '🇸🇴' },
        { label: 'South Africa', value: '(+27)', ccTLD: '🇿🇦' },
        { label: 'South Georgia and the South Sandwich Islands', value: '(+500)', ccTLD: '🇬🇸' },
        { label: 'Spain', value: '(+34)', ccTLD: '🇪🇸' },
        { label: 'Sri Lanka', value: '(+94)', ccTLD: '🇱🇰' },
        { label: 'Sudan', value: '(+249)', ccTLD: '🇸🇩' },
        { label: 'Suriname', value: '(+597)', ccTLD: '🇸🇷' },
        { label: 'Svalbard and Jan Mayen', value: '(+47)', ccTLD: '🇸🇯' },
        { label: 'Swaziland', value: '(+268)', ccTLD: '🇸🇿' },
        { label: 'Sweden', value: '(+46)', ccTLD: '🇸🇪' },
        { label: 'Switzerland', value: '(+41)', ccTLD: '🇨🇭' },
        { label: 'Syrian Arab Republic', value: '(+963)', ccTLD: '🇸🇾' },
        { label: 'Taiwan', value: '(+886)', ccTLD: '🇹🇼' },
        { label: 'Tajikistan', value: '(+992)', ccTLD: '🇹🇯' },
        { label: 'Tanzania', value: '(+255)', ccTLD: '🇹🇿' },
        { label: 'Thailand', value: '(+66)', ccTLD: '🇹🇭' },
        { label: 'Timor-Leste', value: '(+670)', ccTLD: '🇹🇱' },
        { label: 'Togo', value: '(+228)', ccTLD: '🇹🇬' },
        { label: 'Tokelau', value: '(+690)', ccTLD: '🇹🇰' },
        { label: 'Tonga', value: '(+676)', ccTLD: '🇹🇴' },
        { label: 'Trinidad and Tobago', value: '(+1868)', ccTLD: '🇹🇹' },
        { label: 'Tunisia', value: '(+216)', ccTLD: '🇹🇳' },
        { label: 'Turkey', value: '(+90)', ccTLD: '🇹🇷' },
        { label: 'Turkmenistan', value: '(+993)', ccTLD: '🇹🇲' },
        { label: 'Turks and Caicos Islands', value: '(+1649)', ccTLD: '🇹🇨' },
        { label: 'Tuvalu', value: '(+688)', ccTLD: '🇹🇻' },
        { label: 'Uganda', value: '(+256)', ccTLD: '🇺🇬' },
        { label: 'Ukraine', value: '(+380)', ccTLD: '🇺🇦' },
        { label: 'United Arab Emirates', value: '(+971)', ccTLD: '🇦🇪' },
        { label: 'United Kingdom', value: '(+44)', ccTLD: '🇬🇧' },
        { label: 'United States', value: '(+1)', ccTLD: '🇺🇸' },
        { label: 'Uruguay', value: '(+598)', ccTLD: '🇺🇾' },
        { label: 'Uzbekistan', value: '(+998)', ccTLD: '🇺🇿' },
        { label: 'Vanuatu', value: '(+678)', ccTLD: '🇻🇺' },
        { label: 'Venezuela', value: '(+58)', ccTLD: '🇻🇪' },
        { label: 'Vietnam', value: '(+84)', ccTLD: '🇻🇳' },
        { label: 'Virgin Islands, British', value: '(+1284)', ccTLD: '🇻🇬' },
        { label: 'Virgin Islands, U.S.', value: '(+1340)', ccTLD: '🇻🇮' },
        { label: 'Wallis and Futuna', value: '(+681)', ccTLD: '🇼🇫' },
        { label: 'Yemen', value: '(+967)', ccTLD: '🇾🇪' },
        { label: 'Zambia', value: '(+260)', ccTLD: '🇿🇲' },
        { label: 'Zimbabwe', value: '(+263)', ccTLD: '🇿🇼' }
    ];
    
    
    
    
    return(
        <ConfigProvider
            
            theme={{
                token: {
                    colorBgBase: '#f2f2f2', 
                    colorBgTextHover:'#ccc',

                },
                
            }}
        >
        <Select
        showSearch
        className='col-12 border-radius-12'
        style={{height:'3rem'}}
        defaultValue={countries[104]}
        optionFilterProp="children"
        filterOption={(input, option) =>
            option.props.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
        }
        >
        {countries.map(country => (
            <Option key={country.ccTLD} value={country.value} className="ltr light-white-font font-16">
            <span className='countryPopOption' style={{fontVariant:'small-caps'}}>{country.ccTLD}</span> {`${country.label}  ${country.value}`}
            </Option>
        ))}
        </Select>
        </ConfigProvider>
    )
}
        
